import os
import anthropic
from config import ANTHROPIC_API_KEY, ANTHROPIC_MODEL

_client: anthropic.AsyncAnthropic | None = None

def get_client() -> anthropic.AsyncAnthropic:
    """Return a singleton async Anthropic client."""
    global _client
    if _client is None:
        if not ANTHROPIC_API_KEY:
            raise RuntimeError("ANTHROPIC_API_KEY not configured in .env")
        _client = anthropic.AsyncAnthropic(api_key=ANTHROPIC_API_KEY)
    return _client

async def call_claude(prompt: str, system: str = None) -> str:
    """
    Call Claude API with error handling fallback.
    
    Args:
        prompt: User prompt.
        system: Optional system prompt.
        
    Returns:
        String response generated by Claude.
    """
    try:
        client = get_client()
        system_arg = system if system else anthropic.NOT_GIVEN
        
        # Limit max_tokens to 500 per spec
        response = await client.messages.create(
            model=ANTHROPIC_MODEL,
            max_tokens=500,
            system=system_arg,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.content[0].text
    except Exception as e:
        print(f"Claude API Error: {e}")
        return "Model API currently unavailable. Please analyze telemetry manually."
