import json
import urllib.request
import urllib.error
from config import OLLAMA_URL, OLLAMA_MODEL

async def call_ollama(prompt: str, system: str = None) -> str:
    """
    Call Local Ollama API asynchronously.
    
    Args:
        prompt: User prompt.
        system: Optional system prompt.
        
    Returns:
        String response generated by Ollama.
    """
    url = f"{OLLAMA_URL}/api/generate"
    
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }
    
    if system:
        payload["system"] = system
        
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    
    try:
        # Simple HTTP request to local server without heavy dependencies
        with urllib.request.urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode("utf-8"))
            return result.get("response", "")
    except urllib.error.URLError as e:
        print(f"Ollama API Error: {e}")
        return "Local AI model is spinning up or unavailable. Please check if Ollama is running (`ollama run gemma:2b`)."
    except Exception as e:
        print(f"Ollama API Error: {e}")
        return "Error querying local AI model."
